codecov:
  require_ci_to_pass: true
  bot: "2ambot"
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "25...40"
  status:
    project:
      default:
        informational: true
    patch: off

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!master"
  individual_components:
    - component_id: module_core
      name: core
      flag_regexes:
        - "core"
      paths:
        - substrate/**
    - component_id: module_app
      name: app
      flag_regexes:
        - "app"
      paths:
        - app/**
    - component_id: module_commons
      name: commons
      flag_regexes:
        - "commons"
      paths:
        - commons/**
    - component_id: module_engine
      name: engine
      flag_regexes:
        - "engine"
      paths:
        - engine/**

flags:
  core:
    paths:
      - substrate/**/*.*
    carryforward: true
  app:
    paths:
      - app/**/*.*
    carryforward: true

comment:
  layout: "reach,diff,flags,components,files,footer"
  behavior: default
  require_changes: false

parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

bundle_analysis:
  warning_threshold: "10MB"
  status: True

github_checks:
  annotations: true
