version: 2

registries:
  buf:
    type: cargo-registry
    registry: "buf"
    url: https://buf.build/gen/cargo/
    token: "Bearer ${{ secrets.BUF_TOKEN }}"
  buf-npm:
    type: npm-registry
    url: https://buf.build/gen/npm/v1
    token: ${{ secrets.BUF_TOKEN }}
    replaces-base: false

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: cargo
    directory: /
    registries:
      - buf
    schedule:
      interval: weekly

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    registries:
      - buf-npm
    schedule:
      interval: weekly
