[libraries]
commons = { module = "gg.genstack:genstack-commons" }
engine = { module = "gg.genstack:genstack-engine" }
config = { module = "gg.genstack:genstack-config" }
protocol = { module = "gg.genstack:genstack-protocol" }
sdk = { module = "gg.genstack:genstack-sdk" }
