[libraries]
commons = { module = "dev.newco:genstack-commons" }
engine = { module = "dev.newco:genstack-engine" }
config = { module = "dev.newco:genstack-config" }
protocol = { module = "dev.newco:genstack-protocol" }
sdk = { module = "dev.newco:genstack-sdk" }
