name: "Check (Sonar)"

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        description: "SonarCloud Token"
        required: true
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  sonarcloud:
    name: Check (Sonar)
    runs-on: ubuntu-24.04
    steps:
      - name: "Setup: Harden Runner"
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          disable-sudo: true
          egress-policy: audit
          allowed-endpoints: >
            api.github.com:443
            buf.build:443
            github.com:443
      - name: "Setup: Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
          persist-credentials: false
          fetch-depth: 0
      - name: "Scan: SonarCloud"
        uses: SonarSource/sonarqube-scan-action@1b442ee39ac3fa7c2acdd410208dcb2bcfaae6c4 # v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
