name: "CI"

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: read

jobs:
  triage:
    name: "Build"
    uses: ./.github/workflows/job.triage.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read

  build-depgraph:
    name: "Build"
    uses: ./.github/workflows/job.dependency-graph.yml
    secrets: inherit
    permissions:
      contents: write

  check-osv:
    name: "Check"
    uses: "2amlogic/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@main"
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      upload-sarif: false
      fail-on-vuln: false
      scan-args: --config=./.dev/osv.toml --call-analysis=all --lockfile=pnpm-lock.yaml --lockfile=Cargo.lock --lockfile=*/gradle.lockfile

  check-sonar:
    name: "Check"
    uses: ./.github/workflows/check.sonar.yml
    secrets: inherit

  test-all:
    name: "Test"
    needs: [triage]
    uses: ./.github/workflows/job.test.yml
    secrets: inherit
    with:
      #javascript: ${{ fromJson(needs.triage.outputs.javascript || 'false') == true }}
      #jvm: ${{ fromJson(needs.triage.outputs.kotlin || 'false') == true }}
      javascript: true
      jvm: true
