name: "Publish (All - NPM)"

"on":
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        required: false
        description: "Job: Dry Run"

  workflow_call:
    inputs:
      dry-run:
        type: boolean
        required: false
        description: "Job: Dry Run"

    secrets:
      NPM_TOKEN:
        description: "NPM: Token"
        required: true

permissions:
  contents: read

jobs:
  # NPM: `@genstack.js/config`
  publish-npm-config:
    name: "Publish"
    uses: ./.github/workflows/publish.npm.yml
    permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write
    with:
        path: packages/config
        name: "@genstack.js/config"
        dry-run: ${{ inputs.dry-run }}

  # NPM: `@genstack.js/protocol`
  publish-npm-protocol:
    name: "Publish"
    uses: ./.github/workflows/publish.npm.yml
    needs: [publish-npm-config]
    permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write
    with:
        path: packages/protocol
        name: "@genstack.js/protocol"
        dry-run: ${{ inputs.dry-run }}

  # NPM: `@genstack.js/util`
  publish-npm-util:
    name: "Publish"
    uses: ./.github/workflows/publish.npm.yml
    needs: [publish-npm-config, publish-npm-protocol]
    permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write
    with:
        path: packages/util
        name: "@genstack.js/util"
        dry-run: ${{ inputs.dry-run }}

  # NPM: `@genstack.js/memdb`
  publish-npm-memdb:
    name: "Publish"
    uses: ./.github/workflows/publish.npm.yml
    needs: [publish-npm-config, publish-npm-protocol, publish-npm-util]
    permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write
    with:
        path: packages/memdb
        name: "@genstack.js/memdb"
        dry-run: ${{ inputs.dry-run }}

  # NPM: `@genstack.js/sdk`
  publish-npm-sdk:
    name: "Publish"
    uses: ./.github/workflows/publish.npm.yml
    needs: [publish-npm-config, publish-npm-protocol, publish-npm-memdb]
    permissions:
        contents: read
        packages: write
        id-token: write
        attestations: write
    with:
        path: packages/memdb
        name: "@genstack.js/memdb"
        dry-run: ${{ inputs.dry-run }}
